# Generated by Django 5.2.4 on 2025-08-11 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TouristPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/toursitplaces/')),
                ('short_description', models.TextField(blank=True, null=True)),
                ('location_inside_city', models.CharField(blank=True, max_length=255, null=True)),
                ('distance_from_main_city', models.CharField(blank=True, max_length=50, null=True)),
                ('map_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tourist_places', to='core.city')),
            ],
        ),
    ]
