# Generated by Django 5.2.4 on 2025-09-24 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_touristplace'),
    ]

    operations = [
        migrations.CreateModel(
            name='TouristPlaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/touristplaces/extra/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('tourist_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='core.touristplace')),
            ],
        ),
    ]
